package com.va.week6.servlet;

import java.io.IOException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;


import com.va.week6.dao.StudentDao;
import com.va.week6.model.Student;
import com.va.week6.security.Md5HashingClass;
import com.va.week6.security.ShaHashing;

/**
 * Servlet implementation class StudentServlet
 */
@WebServlet("/StudentServlet")
public class StudentServlet extends HttpServlet {
	
	private static final long serialVersionUID = 1L;

	private StudentDao stDao;

	public void init() {
		stDao = new StudentDao();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse
	 *      response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

		String firstName = request.getParameter("firstName");
		String lastName = request.getParameter("lastName");
		String grade = request.getParameter("grade");

		Student st = new Student();
		Md5HashingClass md5 = new Md5HashingClass();
		
		ShaHashing sha = new ShaHashing();
		
		/*
		 *Depending what you want to hash.. you can simply call the method from hashingclass here.. 
		 *for example.
		 */
		//String hashedgrade=md5.getMd5(grade);
		
		String hashedgradeWithSha= sha.encryptThisString(grade);
		
		
		/*  -- call your hashing method here.. 
		 * 		Md5HashingClass md5 = new Md5HashingClass();
				//md5.getMd5(n);  // call the md5 method for hashing the string input - ie. username.. 
				System.out.println("Your HashCode Generated by MD5 is: " + md5.getMd5(n));			
		 */
		
		st.setFirstname(firstName);
		st.setLastname(lastName);
		st.setGrade(hashedgradeWithSha);
		

		try {
		
			
		//	st.setGrade(md5.getMd5(n));
			stDao.registerStudent(st);

			
		} catch (Exception e) {
			e.printStackTrace();
		}
		response.sendRedirect("StudentInfo.jsp");
	}

}
